---
functional:
 - Сайт должен предоставлять возможность двум программистам решать задачи на скорость.
 - Сайт должен предоставлять возможность настраивать время игры, сложность и выбирать определенное задание.
 - Сайт должен позволять игрокам менять язык программирования во время игры. Поддерживаемые языки Clojure, C#, C++, Dart, Elixir, Golang, Haskell, Java, JavaScript, Kotlin, PHP, Python, Ruby, Rust, Typescript.
 - Сайт должен предоставлять возможность игры с любым человеком, другом по ссылке или ботом.
 - Сайт должен предоставлять чат для общения зарегистрированных пользователей.
 - Сайт должен сохранять и предоставлять доступ к записям завершённых игр с интерфейсом проигрывателя кода.
 - Сайт должен начислять очки игрокам и вести рейтинг за неделю, месяц и всё время.
 - Сайт должен поддерживать интерфейс и задачи на русском и английском языках.
 - Сайт должен поддерживать возможность создание своего аккаунта и авторизации в него в дальнейшем.
 - Сайт должен поддерживать возможность авторизации через GitHub и Discord.
 - Сайт должен позволять пользователю создать турнир
non-functional:
 - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен иметь мобильную версию.
 - Сайт должен быть протестирован на совместимость с последними версиями браузеров. Поддерживаемые браузеры Opera, Mozilla, Chrome, Safari, Edge.
 - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
 - Сайт должен стимулировать возвращение пользователей через систему рейтингов и очков.
 - Сайт должен быть интуитивно понятным и удобным как для новичков, так и для опытных пользователей.
 - Сайт должен поддерживать проведение турниров и соревновательных мероприятий.
 - Сайт должен включать социальные функции, такие как игра с друзьями и возможность наблюдения за играми.
